"""Migracion limpia

Revision ID: 0292dbec0b49
Revises: 
Create Date: 2025-09-23 12:35:50.088042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0292dbec0b49'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insumos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo_producto', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('existencias_iniciales_anio', sa.Integer(), nullable=True),
    sa.Column('stock_actual', sa.Integer(), nullable=True),
    sa.Column('porcentaje_utilizado', sa.Float(), nullable=True),
    sa.Column('cantidad_entradas', sa.Integer(), nullable=True),
    sa.Column('cantidad_salidas', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_producto')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cedula', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('dependencia', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('cedula')
    )
    op.create_table('entrada_insumos',
    sa.Column('id_entrada', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_entrada', sa.Date(), nullable=True),
    sa.Column('proveedor', sa.String(length=100), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('insumo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['insumo_id'], ['insumos.id'], ),
    sa.PrimaryKeyConstraint('id_entrada')
    )
    op.create_table('salida_insumos',
    sa.Column('id_salida', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cantidad_solicitada', sa.Integer(), nullable=False),
    sa.Column('cantidad_entregada', sa.Integer(), nullable=False),
    sa.Column('fecha_salida', sa.Date(), nullable=True),
    sa.Column('insumo_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['insumo_id'], ['insumos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_salida')
    )
    op.create_table('solicitud_insumos',
    sa.Column('id_solicitud', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_solicitud', sa.DateTime(), nullable=True),
    sa.Column('cantidad_solicitada', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('observaciones', sa.String(length=200), nullable=True),
    sa.Column('insumo_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['insumo_id'], ['insumos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_solicitud')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitud_insumos')
    op.drop_table('salida_insumos')
    op.drop_table('entrada_insumos')
    op.drop_table('usuarios')
    op.drop_table('insumos')
    # ### end Alembic commands ###
