"""Añadimos campos de auditoria

Revision ID: 5952a8d445a1
Revises: c0f0561926dc
Create Date: 2026-03-26 11:45:49.465928

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5952a8d445a1'
down_revision = 'c0f0561926dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('accion', sa.Enum('LOGIN_EXITOSO', 'LOGIN_FALLIDO', 'LOGOUT', 'CAMBIO_CONTRASEÑA', 'CARGA_INSUMO', 'CARGA_MULTIPLE', 'IMPORTACION_CSV', 'SALIDA_STOCK', 'CREAR_SOLICITUD', 'EXPORTACION_CSV', name='auditaccion'), nullable=False),
    sa.Column('entidad_tipo', sa.String(length=50), nullable=True),
    sa.Column('entidad_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('EXITOSO', 'FALLIDO', name='auditestado'), nullable=False),
    sa.Column('detalle_json', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_accion'), ['accion'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id_usuario'), ['id_usuario'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('entrada_insumos', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('insumos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('insumos_created_by_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('insumos_updated_by_fkey'), type_='foreignkey')
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_by')

    with op.batch_alter_table('salidas_insumos', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))

    with op.batch_alter_table('salidas_insumos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))

    with op.batch_alter_table('insumos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('insumos_updated_by_fkey'), 'usuarios', ['updated_by'], ['id_usuario'])
        batch_op.create_foreign_key(batch_op.f('insumos_created_by_fkey'), 'usuarios', ['created_by'], ['id_usuario'])

    with op.batch_alter_table('entrada_insumos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id_usuario'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_accion'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
