"""Normalizacion de la base de datos

Revision ID: b8bb433991fd
Revises: 
Create Date: 2025-10-01 11:01:06.788151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8bb433991fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dependencia',
    sa.Column('id_dependencia', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_dependencia', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_dependencia'),
    sa.UniqueConstraint('nombre_dependencia')
    )
    op.create_table('insumos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo_insumo', sa.String(length=10), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('existencias_iniciales_anio', sa.Integer(), nullable=True),
    sa.Column('stock_actual', sa.Integer(), nullable=True),
    sa.Column('porcentaje_utilizado', sa.Integer(), nullable=True),
    sa.Column('cantidad_entradas', sa.Integer(), nullable=True),
    sa.Column('cantidad_salidas', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_insumo')
    )
    op.create_table('proveedores',
    sa.Column('id_proveedor', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_proveedor'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('roles',
    sa.Column('id_rol', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_rol', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('nombre_rol')
    )
    op.create_table('entrada_insumos',
    sa.Column('id_entrada', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_entrada', sa.Date(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('id_insumo', sa.Integer(), nullable=False),
    sa.Column('id_proveedor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_insumo'], ['insumos.id'], ),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores.id_proveedor'], ),
    sa.PrimaryKeyConstraint('id_entrada')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cedula', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('id_dependencia', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_dependencia'], ['dependencia.id_dependencia'], ),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('cedula')
    )
    op.create_table('solicitudes',
    sa.Column('id_solicitud', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_solicitud', sa.Date(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_solicitud')
    )
    op.create_table('solicitudes_insumos',
    sa.Column('id_solicitudes_insumos', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cantidad_solicitada', sa.Integer(), nullable=False),
    sa.Column('id_solicitud', sa.Integer(), nullable=False),
    sa.Column('id_insumo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_insumo'], ['insumos.id'], ),
    sa.ForeignKeyConstraint(['id_solicitud'], ['solicitudes.id_solicitud'], ),
    sa.PrimaryKeyConstraint('id_solicitudes_insumos')
    )
    op.create_table('salidas_insumos',
    sa.Column('id_salida', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cantidad_entregada', sa.Integer(), nullable=False),
    sa.Column('fecha_salida', sa.Date(), nullable=True),
    sa.Column('observaciones', sa.String(length=150), nullable=True),
    sa.Column('id_insumo', sa.Integer(), nullable=False),
    sa.Column('id_solicitudes_insumos', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_insumo'], ['insumos.id'], ),
    sa.ForeignKeyConstraint(['id_solicitudes_insumos'], ['solicitudes_insumos.id_solicitudes_insumos'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_salida')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salidas_insumos')
    op.drop_table('solicitudes_insumos')
    op.drop_table('solicitudes')
    op.drop_table('usuarios')
    op.drop_table('entrada_insumos')
    op.drop_table('roles')
    op.drop_table('proveedores')
    op.drop_table('insumos')
    op.drop_table('dependencia')
    # ### end Alembic commands ###
